os: linux
language: python
jobs:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
cache: pip
git:
  depth: false
dist: xenial
# command to install dependencies
install:
  - pip install -U tox-travis setuptools
# command to run tests
script: tox
notifications:
  irc:
    channels:
      - "chat.freenode.net#dosage"
    use_notice: true
    skip_join: true
